// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type LoginReq struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
	Token string `json:"token,optional"`
}

type LoginResp struct {
	Token  string `json:"token"`
	UserId int64  `json:"userId"`
}

type SendSmsReq struct {
	Phone string `json:"phone"`
}
