// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConversationMember = "conversation_member"

// ConversationMember mapped from table <conversation_member>
type ConversationMember struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`           // 主键ID
	ConversationID int64     `gorm:"column:conversation_id;not null;comment:会话ID" json:"conversation_id"`      // 会话ID
	UserID         int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                      // 用户ID
	Role           string    `gorm:"column:role;default:member;comment:用户在群组中的角色" json:"role"`                 // 用户在群组中的角色
	JoinedAt       time.Time `gorm:"column:joined_at;default:CURRENT_TIMESTAMP;comment:加入时间" json:"joined_at"` // 加入时间
}

// TableName ConversationMember's table name
func (*ConversationMember) TableName() string {
	return TableNameConversationMember
}
