// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConversation = "conversation"

// Conversation mapped from table <conversation>
type Conversation struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:会话ID" json:"id"`             // 会话ID
	Name      string    `gorm:"column:name;not null;comment:会话名称（群聊时有值，私聊为空）" json:"name"`                  // 会话名称（群聊时有值，私聊为空）
	Type      string    `gorm:"column:type;not null;comment:会话类型：private 私聊 / group 群聊" json:"type"`        // 会话类型：private 私聊 / group 群聊
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName Conversation's table name
func (*Conversation) TableName() string {
	return TableNameConversation
}
