// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFriendship = "friendship"

// Friendship mapped from table <friendship>
type Friendship struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`             // 主键ID
	User1ID   int64     `gorm:"column:user1_id;not null;comment:用户1 ID" json:"user1_id"`                    // 用户1 ID
	User2ID   int64     `gorm:"column:user2_id;not null;comment:用户2 ID" json:"user2_id"`                    // 用户2 ID
	Status    string    `gorm:"column:status;not null;default:pending;comment:好友状态" json:"status"`          // 好友状态
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:添加时间" json:"created_at"` // 添加时间
}

// TableName Friendship's table name
func (*Friendship) TableName() string {
	return TableNameFriendship
}
