// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:消息ID" json:"id"`             // 消息ID
	ConversationID int64     `gorm:"column:conversation_id;not null;comment:所属会话ID" json:"conversation_id"`      // 所属会话ID
	SenderID       int64     `gorm:"column:sender_id;not null;comment:发送者ID" json:"sender_id"`                   // 发送者ID
	Content        string    `gorm:"column:content;not null;comment:消息内容" json:"content"`                        // 消息内容
	MessageType    string    `gorm:"column:message_type;not null;default:text;comment:消息类型" json:"message_type"` // 消息类型
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:发送时间" json:"created_at"` // 发送时间
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
