// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageStatus = "message_status"

// MessageStatus mapped from table <message_status>
type MessageStatus struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"` // 主键ID
	MessageID int64     `gorm:"column:message_id;not null;comment:消息ID" json:"message_id"`      // 消息ID
	UserID    int64     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`            // 用户ID
	Status    string    `gorm:"column:status;default:unread;comment:消息状态" json:"status"`        // 消息状态
	ReadAt    time.Time `gorm:"column:read_at;comment:阅读时间" json:"read_at"`                     // 阅读时间
}

// TableName MessageStatus's table name
func (*MessageStatus) TableName() string {
	return TableNameMessageStatus
}
